# Hayai Configuration File
# This file contains global settings for the Hayai CLI tool

# Default settings
defaults:
  port_range:
    min: 5000
    max: 9999
  persistence: true
  generate_client: false
  enable_studio: false
  
# Database templates directory
templates_dir: "./templates"

# Docker settings
docker:
  compose_file: "docker-compose.yml"
  network_name: "hayai-network"
  
# Studio settings
studio:
  port: 8080
  enabled: false
  
# Logging settings
logging:
  level: "info"
  file: "hayai.log" 