version: '1.0.0'
docker:
  network_name: 'hayai-network'
  compose_file: 'docker-compose.yml'
  data_directory: './data'
logging:
  level: 'info'
  file: 'hayai.log'
defaults:
  port_range:
    start: 5000
    end: 6000
  volume_driver: 'local'
  restart_policy: 'unless-stopped' 